services:
  elasticsearch:
    container_name: elasticsearch
    #image: registry1.dso.mil/ironbank/elastic/elasticsearch/elasticsearch:7.14.0
    image: 7e115794031f
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
    networks:
      - elk
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
    restart: on-failure:5
    
  kibana:
    container_name: kibana
    #image: registry1.dso.mil/ironbank/elastic/kibana/kibana:7.14.0
    image: 31dff7ec33fb
    ports:
      - 5601:5601
    networks:
      - elk
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    depends_on:
      - elasticsearch
    restart: on-failure:5

  logstash:
    container_name: logstash
    #image: registry1.dso.mil/ironbank/elastic/logstash/logstash:7.14.0
    image: 
    ports:
      - 5044:5044
      - 5000:5000/tcp
      - 5000:5000/udp
      - 6900:9600
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
    networks:
      - elk
    depends_on: 
      - elasticsearch
    restart: on-failure:5

networks:
  elk:
    driver: bridge
